### ISSUE TITLE
没跑起来 - -

### ISSUE THREAD

**Issue by 41018843** [foxpage/foxpage#10]
nodejs 必须 16 以下吗?
反正没装上 - -

**Comment by WangYiLong** [comment]
是否可以提供多一点信息？我们这边排查下

**Comment by 41018843** [comment]
按手册,没启动!  nodejs 要求版本多少?

**Comment by yhdeng** [comment]
nodejs版本要求是高于14.15.1就可以，没有启动成功的话，有什么提示的信息吗？

**Comment by 41018843** [comment]
脚手架没成功..
![1656646657281](https://user-images.githubusercontent.com/16398321/176818667-196aa183-d298-4d56-9f1f-fcac3c41a080.jpg)

**Comment by 41018843** [comment]
![1656646797824](https://user-images.githubusercontent.com/16398321/176819016-8a2691a0-c1d9-4f8d-92c9-1b4124bf8b07.jpg)

**Comment by yhdeng** [comment]
我本地复现了你这个问题，看来是16的版本和node-sass的版本不兼容导致，你可以用14的版本试下，兼容问题我们处理下。

**Comment by 41018843** [comment]
您这边可以给一个,您这用的node版本号吗 ?

**Comment by 41018843** [comment]
3200端口那个页面,,,用户名密码是啥呀....

**Comment by 41018843** [comment]
UnhandledPromiseRejectionWarning: Error: Run mongo transaction error:This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
    at OrgModel.exec (D:\WGF\SoftWare\自己的\foxpage\foxpage\foxpage-server\dist\src\models\base-model.js:42:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async OrgService.runTransaction (D:\WGF\SoftWare\自己的\foxpage\foxpage\foxpage-server\dist\src\services\base-service.js:15:9)
    at async setupSql (D:\WGF\SoftWare\自己的\foxpage\foxpage\foxpage-server\dist\install.js:71:9)
    at async install (D:\WGF\SoftWare\自己的\foxpage\foxpage\foxpage-server\dist\install.js:38:28)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
这个,mongo DB ...需要启动两个节点..这玩意,没用过..好像很麻烦呀..没整明白....

**Comment by melodyJie** [comment]
> jections that are not handled will terminate the Node.js process with a non-zero exit code.
> 这个,mongo DB ...需要启动两个节点..这玩意,没用过..好像很麻烦呀..没整明白....

node16 兼容问题，已在  [@foxpage/foxpage-cli](https://github.com/foxpage/foxpage-cli)  0.3.2版本中修复

**Comment by melodyJie** [comment]
> 脚手架没成功.. ![1656646657281](https://user-images.githubusercontent.com/16398321/176818667-196aa183-d298-4d56-9f1f-fcac3c41a080.jpg)

node16 兼容问题，已在 [@foxpage/foxpage-cli](https://github.com/foxpage/foxpage-cli) 0.3.2版本中修复

**Comment by 41018843** [comment]
必须要mongoDb吗 ^_^

**Comment by yhdeng** [comment]
是的，现在只支持了mongodb

**Comment by 41018843** [comment]
> 是的，现在只支持了mongodb

感谢您的回复,mongodb这玩意实属没整明白,

**Comment by yhdeng** [comment]
mongodb 可以考虑使用docker启动下2个节点，这种比较方便

**Comment by 41018843** [comment]
> mongodb 可以考虑使用docker启动下2个节点，这种比较方便

没用那个,,,,我们用的..mysql...sql.多些.....主要是..2节点不会配置

**Comment by inier** [comment]
具体怎么配置2个节点呢？能提供个操作手册么？

**Comment by yhdeng** [comment]
使用docker的话，可以参考https://www.cnblogs.com/hahaha111122222/p/13937264.html
window上直接安装mongodb的话，可以参考https://blog.csdn.net/MrKorbin/article/details/118709066

**Comment by 41018843** [comment]
根据上面的资料,,多点启动完成,也可以登录页面,,,但.之后显示空白,然后,控制台出错误信息
![image](https://user-images.githubusercontent.com/16398321/177891549-71ebff4a-10ef-47ee-9097-95b96b52b3e0.png)

**Comment by 41018843** [comment]
这个是 admin 启动信息,,也有警告
![image](https://user-images.githubusercontent.com/16398321/177891619-8a0d7c3e-5c5b-4193-be9f-c998e9447b94.png)

**Comment by drxiao1** [comment]
@41018843  不好意思，让你久等了。

该问题目前已经解决，可以试着重新更新试下。

目前我们版本在迭代中，文档上可能有点滞后，后续我们会加紧补上。

为了快速响应你的问题，可以加下我们的技术群，群里会快速响应的。
![image](https://user-images.githubusercontent.com/22312959/177972116-db073073-c5a9-4afb-b380-a3cef0b571ba.png)

**Comment by ccclllll** [comment]
@drxiao1 入群二维码失效了，可以再提供一个吗

**Comment by yhdeng** [comment]
@ccclllll 
![86785684505d00fa10a999857c56b76](https://user-images.githubusercontent.com/6350107/179973059-2a83b93d-7ffb-4426-9adc-9dc6a58df847.png)

**Comment by Ouchuxuan** [comment]
@yhdeng 大佬能更新下微信技术群二维码吗，我想进群请教点问题，感谢
